language: go

os:
  - linux
  - osx

go:
  - "1.10.x"
  - master

stages:
  - lint
  - build

jobs:
  include:
    - stage: lint
      script:
        - go get github.com/golang/lint/golint
        - golint
        - go vet
    - stage: build
      script:
        - if [ $TRAVIS_OS_NAME == linux ]; then go build -o goddi; fi
        - if [ $TRAVIS_OS_NAME == osx ]; then go build -o goddi; fi
      after_success:
        - chmod +x goddi
        - ./goddi

matrix:
  include:
    - os: osx
    - os: linux
  allow_failures:
    - go: master
  fast_finish: true
